---
title: "Trend_Plots"
author: "S. Sillen"
date: '2022-07-07'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Required packages
```{r}
library(leaflet)
library(tidyverse)

```

```{r}
trends <- read.csv("C:/Users/samsi/Dropbox/WesternMountainsChlPreds/trends.csv") %>%
  select(lagoslakeid, trend)

preds <- read.csv("C:/Users/samsi/Dropbox/preds.csv")

trend_data <- preds %>%
  filter(lagoslakeid %in% trends$lagoslakeid)

trend_data <- left_join(trend_data, trends, by = 'lagoslakeid')

trend_data <- trend_data %>%
  distinct(lagoslakeid, lake_lat_decdeg, lake_lon_decdeg, lake_elevation_m, trend, WetIndexCat, Tmean8110Cat, ClayCat, OmCat, PermCat, RckdepCat, BFICat, CatAreaSqKm, PctAg2006Slp10Cat, NPDESDensCat, HydrlCondCat, PctImp2006Cat, PctUrbLo2006Cat, PctUrbMd2006Cat, PctUrbHi2006Cat, PctDecid2006Cat, PctConif2006Cat, PctMxFst2006Cat, PctWdWet2006Cat, PctHbWet2006Cat, PctCrop2006Cat, KffactCat, NO3_2008Cat, RunoffCat, WtDepCat)

trend_data <- trend_data %>%
  distinct(lagoslakeid, .keep_all = TRUE)
```

#Leaflet map
```{r}

pal <- colorFactor(c( '#2158bc',  '#698c86', '#7dae38'), domain = c("improving", "no change", "worsening" ))

trend_data$trend <- factor(trend_data$trend, levels = c('no change', 'improving', 'worsening'))


map <- leaflet(data = trend_data) %>%
  addProviderTiles(providers$Esri.WorldTopoMap) %>%
addCircleMarkers(lat = trend_data$lake_lon_decdeg, lng = trend_data$lake_lat_decdeg,
    color = ~pal(trend),
    stroke = FALSE, fillOpacity = 1,
    radius = 5
  )

map %>% 
  addLegend("bottomright", pal = pal, values = ~trend)

```

```{r}

trend_data2 <- trend_data2 %>%
  mutate(Development = PctUrbHi2006Cat + PctUrbLo2006Cat + PctUrbMd2006Cat, 
         Forest = PctMxFst2006Cat + PctDecid2006Cat + PctConif2006Cat)

vars.long <- trend_data2 %>% pivot_longer(cols = c("lake_elevation_m",  "Tmean8110Cat",      "ClayCat",          
"OmCat",             "PermCat",           "RckdepCat",
"BFICat",           "CatAreaSqKm",       "PctAg2006Slp10Cat",
"NPDESDensCat",      "HydrlCondCat",      "PctImp2006Cat",  
"PctCrop2006Cat", "PctWdWet2006Cat", "PctHbWet2006Cat",
"KffactCat",         "NO3_2008Cat",       "RunoffCat", 
"WtDepCat",          "WetIndexCat", "Forest", "Development", "Vol_total", "Depth_avg", "Dis_avg", "Res_time"), names_to = 'Variable')

unique(vars.long$Variable)

renamer <- tibble(Variable = c(
"lake_elevation_m",  "Tmean8110Cat",      "ClayCat",          
"OmCat",             "PermCat",           "RckdepCat",
"BFICat",           "CatAreaSqKm",       "PctAg2006Slp10Cat",
"NPDESDensCat",      "HydrlCondCat",      "PctImp2006Cat",  
"PctCrop2006Cat", "PctWdWet2006Cat", "PctHbWet2006Cat",
"KffactCat",         "NO3_2008Cat",       "RunoffCat", 
"WtDepCat",          "WetIndexCat", "Development", "Forest", "Vol_total", "Depth_avg", "Dis_avg", "Res_time"),

namesNew = c(
"Lake Elevation (m)",  "30 Year Normal Mean Temp",      "Mean % Clay Cotent",          
"Mean % Organic Matter",             "Mean Permeability of Soils (cm/hour)",           "Mean Depth to Bedrock (cm)",
"Base Flow Index (% of Total Flow)",           "Area of Catchment (Sq Km)",       "% Agricultural Land on Slopes > 20%",
"Density of Permitted NPDES Sites (Sites / Sq Km)",      "Mean Hydraulic Conductivity (um/sec)",      "% Impervious Cover",  
"% Cropland", "Percent Woody Wetland", "Percent Herbaceous Wetland",
"Kffactor",         "Mean Wet Deposition of Nitrate (kg/ha/yr)",       "Mean Runoff (mm)", 
"Mean Water Table Depth (cm)",          "Mean Composite Topographic Index", "% Development", "% Forest", "Total Volume (million cubic meters)", "Average Depth", "Inflow (cms)", "Residence Time (days)")) 


vars.long2 <- vars.long %>%
  left_join(renamer)


vars.long <- vars.long %>%
  select(-lake_lat_decdeg, -lake_lon_decdeg)

vars.long$value <- signif(vars.long$value, digits = 5)

vars.long2 <- vars.long2 %>%
  drop_na()

lms <- vars.long %>% 
  mutate(totalChange = as.numeric(as.factor((trend)))) %>%
  group_by(Variable) %>% 
  nest() %>%
  mutate(lm = purrr::map(data, ~lm(totalChange ~ value, .)),
         summary = purrr::map(lm, broom::tidy)) %>%
  select(-c(data,lm)) %>%
  unnest(summary)

view(lms %>% filter(term == 'value'))

sig <- (lms %>% filter(term == 'value', p.value > 0.05))


p_value <- vars.long %>%
  filter(Variable %in% sig$Variable)


plots <- vars.long2 %>%
  filter(Variable %in% c('Vol_total', 'Depth_avg', 'Res_time', 'Forest', 'Development', 'PctCrop2006Cat'))


stab.sum <- plots %>%
  select(trend, namesNew, value) %>%
  group_by(trend, namesNew) %>%
  summarise(quant25 = quantile(value, .25, na.rm = T),
            quant75 = quantile(value, .75, na.rm = T),
            median = median(value, na.rm = T)) %>% ungroup()

stab.sum$trend <- factor(stab.sum$trend, levels = c("no change", "improving", "worsening"))

stab.sum %>%
  ggplot(aes(x = trend, y = median)) +
  #geom_point() +
  #geom_pointrange(aes(ymin = quant25, ymax = quant75)) +
  geom_crossbar(aes(ymin = quant25, ymax = quant75), fill = 'grey95') +
  theme_bw()+
  theme(panel.grid.minor = element_blank(), axis.title.y  = element_blank()) +
  facet_wrap(~namesNew, scales = 'free', labeller = labeller(namesNew = label_wrap_gen(15))) 

```

